### ISSUE TITLE
DNode 资源使用情况

### ISSUE THREAD

**Issue by duyingsoft** [taosdata/taoskeeper#28]
集群有三个节点，第一个节点安装了taoskeeper，但是grafana上的报表“DNode 资源使用情况”只有第一个节点data1有监控信息
![image](https://user-images.githubusercontent.com/13470619/228188300-41f39a6e-964b-463c-80d4-956dafa21080.png)

这个是需要每个节点都安装taoskeeper吗？

**Comment by sangshuduo** [comment]
如果需要用一个 taoskeeper，其他节点需要修改配置并指向这个 taoskeeper

**Comment by duyingsoft** [comment]
> 如果需要用一个 taoskeeper，其他节点需要修改配置并指向这个 taoskeeper
(1) 这个修改配置指向这个 taoskeeper是修改哪里的？好像不是很清楚，有参考说明吗
(2) 每个节点都装taoskeeper，也是可以吗？会有其他问题吗

**Comment by duyingsoft** [comment]
> 如果需要用一个 taoskeeper，其他节点需要修改配置并指向这个 taoskeeper

(1) 这个修改配置指向这个 taoskeeper是修改哪里的？好像不是很清楚，能麻烦给个参考说明吗
(2) 每个节点都装taoskeeper，也是可以吗？会有其他问题吗
