### ISSUE TITLE
go mod tidy 就过不去怎么办？

### ISSUE THREAD

**Issue by bohell** [taosdata/taoskeeper#9]
1. check sum 各种报错，最后只好手动调成一致
2.  要求influxdata/telegraf@v1.23.3  但是它又要求harlow/kinesis-consumer v0.3.6 ，但是这个版本被作者删了，根本都不存在了，也不知的怎么改，我就把telegraf版本改成1.24.0 不知道最后行不行
3. influxdata/telegraf改成1.24.0之后，requires  google.golang.org/grpc/naming@v0.0.0-00010101000000-000000000000 一个什么很奇怪的版本，也是根本找不到的，现在就卡在这里，根本没法继续安装了.....

求教程

**Comment by sangshuduo** [comment]
$ time go mod tidy
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/BurntSushi/toml v0.4.1
go: downloading github.com/spf13/viper v1.12.0
go: downloading github.com/taosdata/go-utils v0.0.0-20211022070036-018cc5f2432a
go: downloading github.com/stretchr/testify v1.7.4
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/shirou/gopsutil v3.21.11+incompatible
go: downloading github.com/gin-gonic/gin v1.7.4
go: downloading github.com/influxdata/telegraf v1.23.3
go: downloading github.com/prometheus/client_golang v1.12.2
go: downloading github.com/shopspring/decimal v1.3.1
go: downloading github.com/taosdata/driver-go/v3 v3.0.0-20220707070353-31ea371e8aa0
go: downloading github.com/panjf2000/ants/v2 v2.4.6
go: downloading golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f
go: downloading github.com/gin-contrib/cors v1.3.1
go: downloading github.com/gin-contrib/gzip v0.0.3
go: downloading github.com/gin-contrib/pprof v1.3.0
go: downloading github.com/fsnotify/fsnotify v1.5.4
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.8.2
go: downloading github.com/spf13/cast v1.5.0
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/sys v0.0.0-20220610221304-9f5ed59c137d
go: downloading github.com/tklauser/go-sysconf v0.3.10
go: downloading github.com/gin-contrib/sse v0.1.0
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/common v0.32.1
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/json-iterator/go v1.1.12
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/subosito/gotenv v1.3.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.66.4
go: downloading github.com/magiconair/properties v1.8.6
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading github.com/pelletier/go-toml/v2 v2.0.1
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/ghodss/yaml v1.0.1-0.20190212211648-25d852aebe32
go: downloading github.com/hashicorp/consul/api v1.12.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading k8s.io/api v0.24.2
go: downloading k8s.io/apimachinery v0.24.2
go: downloading k8s.io/client-go v0.24.1
go: downloading github.com/yusufpapurcu/wmi v1.2.2
go: downloading github.com/go-playground/validator/v10 v10.4.1
go: downloading github.com/ugorji/go/codec v1.1.7
go: downloading github.com/tklauser/numcpus v0.4.0
go: downloading github.com/google/go-cmp v0.5.8
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/alecthomas/units v0.0.0-20210208195552-ff826a37aa15
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/influxdata/toml v0.0.0-20190415235208-270119a8ce65
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/hashicorp/go-hclog v1.2.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.2
go: downloading github.com/hashicorp/serf v0.9.7
go: downloading github.com/frankban/quicktest v1.14.3
go: downloading gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: downloading github.com/hashicorp/consul/sdk v0.8.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading k8s.io/klog/v2 v2.60.1
go: downloading k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
go: downloading golang.org/x/net v0.0.0-20220607020251-c690dde0001d
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/testcontainers/testcontainers-go v0.12.0
go: downloading github.com/go-ole/go-ole v1.2.6
go: downloading github.com/go-playground/universal-translator v0.17.0
go: downloading github.com/leodido/go-urn v1.2.0
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/go-playground/assert/v2 v2.0.1
go: downloading github.com/go-playground/locales v0.13.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/tidwall/gjson v1.14.1
go: downloading github.com/naoina/go-stringutil v0.1.0
go: downloading github.com/kylelemons/godebug v1.1.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/armon/go-metrics v0.3.10
go: downloading github.com/kr/pretty v0.3.0
go: downloading github.com/hashicorp/go-msgpack v0.5.5
go: downloading github.com/hashicorp/memberlist v0.3.0
go: downloading github.com/stretchr/objx v0.4.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.1
go: downloading sigs.k8s.io/json v0.0.0-20211208200746-9f7c6b3444d2
go: downloading github.com/go-logr/logr v1.2.3
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading golang.org/x/time v0.0.0-20220609170525-579cf78fd858
go: downloading golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
go: downloading golang.org/x/oauth2 v0.0.0-20220608161450-d0670ef3b1eb
go: downloading k8s.io/kube-openapi v0.0.0-20220328201542-3ee0da9b0b42
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading github.com/docker/docker v20.10.17+incompatible
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/moby/term v0.0.0-20201216013528-df9cb8a40635
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/dimchansky/utfbom v1.1.1
go: downloading collectd.org v0.5.0
go: downloading github.com/vjeantet/grok v1.0.1
go: downloading github.com/influxdata/line-protocol/v2 v2.2.1
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/prometheus/prometheus v1.8.2-0.20210430082741-2a4b8e12bbf2
go: downloading github.com/tinylib/msgp v1.1.6
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/antchfx/jsonquery v1.2.0
go: downloading github.com/antchfx/xmlquery v1.3.9
go: downloading github.com/antchfx/xpath v1.2.1
go: downloading github.com/doclambda/protobufquery v0.0.0-20210317203640-88ffabe06a60
go: downloading github.com/jhump/protoreflect v1.8.3-0.20210616212123-6cc1efa697ca
go: downloading github.com/hashicorp/go-immutable-radix v1.3.1
go: downloading github.com/pascaldekloe/goe v0.1.0
go: downloading github.com/kr/text v0.2.0
go: downloading github.com/rogpeppe/go-internal v1.6.2
go: downloading github.com/google/btree v1.0.1
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/miekg/dns v1.1.48
go: downloading github.com/sean-/seed v0.0.0-20170313163322-e2103e2c3529
go: downloading github.com/mitchellh/go-testing-interface v1.0.0
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/go-openapi/swag v0.19.15
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/opencontainers/image-spec v1.0.2
go: downloading github.com/morikuni/aec v1.0.0
go: downloading github.com/containerd/containerd v1.5.13
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/bmatcuk/doublestar/v3 v3.0.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/wavefronthq/wavefront-sdk-go v0.9.11
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/influxdata/line-protocol-corpus v0.0.0-20210922080147-aa28ccfb8937
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading google.golang.org/genproto v0.0.0-20220617124728-180714bec0ad
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading google.golang.org/appengine v1.6.7
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading github.com/go-openapi/jsonreference v0.19.5
go: downloading golang.org/x/tools v0.1.9
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/opencontainers/runc v1.1.2
go: downloading github.com/Microsoft/hcsshim v0.8.24
go: downloading github.com/moby/sys/mount v0.2.0
go: downloading github.com/Microsoft/go-winio v0.4.17
go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
go: downloading go.uber.org/atomic v1.9.0
go: downloading github.com/onsi/ginkgo v1.16.4
go: downloading github.com/onsi/gomega v1.15.0
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/moby/sys/mountinfo v0.5.0
go: downloading github.com/caio/go-tdigest v3.1.0+incompatible
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/nxadm/tail v1.4.8
go: downloading github.com/containerd/cgroups v1.0.3
go: downloading github.com/leesper/go_rng v0.0.0-20190531154944-a612b043e353
go: downloading gonum.org/v1/gonum v0.11.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading golang.org/x/xerrors v0.0.0-20220609144429-65e65417b02f
go: downloading golang.org/x/mod v0.5.1
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/ugorji/go v1.1.7
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/influxdata/line-protocol v0.0.0-20180522152040-32c6aa80de5e

real    0m21.674s
user    0m10.894s
sys     0m2.973s
shuduo@norepeat ~/work/taosdata/taoskeeper (master)6484ede$ time go build

real    0m51.588s
user    2m45.083s
sys     0m15.992s
shuduo@norepeat ~/work/taosdata/taoskeeper (master)6484ede$ go version
go version go1.18.1 linux/amd64

我没问题

**Comment by diggozuo** [comment]
使用的是
go version go1.19.2 linux/amd64

执行go mod tidy命令时：
github.com/taosdata/taoskeeper/api imports
        github.com/influxdata/telegraf/plugins/inputs/prometheus imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1 imports
        k8s.io/client-go/applyconfigurations/admissionregistration/v1 imports
        k8s.io/apimachinery/pkg/util/managedfields imports
        k8s.io/kube-openapi/pkg/util/proto tested by
        k8s.io/kube-openapi/pkg/util/proto.test imports
        github.com/onsi/gomega imports
        github.com/onsi/gomega/matchers imports
        github.com/onsi/gomega/matchers/support/goraph/bipartitegraph imports
        github.com/onsi/gomega/matchers/support/goraph/util loaded from github.com/onsi/gomega@v1.10.1,
        but go 1.16 would select v1.15.0

To upgrade to the versions selected by go 1.16, leaving some packages unresolved:
        go mod tidy -e -go=1.16 && go mod tidy -e -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17

安装taoskeeper时，建议使用go的哪个版本？

**Comment by diggozuo** [comment]
使用的是
go version go1.19.2 linux/amd64

执行go mod tidy命令时：
github.com/taosdata/taoskeeper/api imports
        github.com/influxdata/telegraf/plugins/inputs/prometheus imports
        k8s.io/client-go/kubernetes imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1 imports
        k8s.io/client-go/applyconfigurations/admissionregistration/v1 imports
        k8s.io/apimachinery/pkg/util/managedfields imports
        k8s.io/kube-openapi/pkg/util/proto tested by
        k8s.io/kube-openapi/pkg/util/proto.test imports
        github.com/onsi/gomega imports
        github.com/onsi/gomega/matchers imports
        github.com/onsi/gomega/matchers/support/goraph/bipartitegraph imports
        github.com/onsi/gomega/matchers/support/goraph/util loaded from github.com/onsi/gomega@v1.10.1,
        but go 1.16 would select v1.15.0

To upgrade to the versions selected by go 1.16, leaving some packages unresolved:
        go mod tidy -e -go=1.16 && go mod tidy -e -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17

安装taoskeeper时，建议使用go的哪个版本？谢谢

**Comment by huolibo** [comment]
由于没有使用特别版本特性，原则上对 GO 版本有没有强制要求。
可以参考本仓库 github action。使用 GO 1.17 版本，在ubuntu系统上是没问题。[compile result](https://github.com/taosdata/taoskeeper/actions/runs/3088874181/jobs/4995854268)

**Comment by diggozuo** [comment]
> 由于没有使用特别版本特性，原则上对 GO 版本有没有强制要求。 可以参考本仓库 github action。使用 GO 1.17 版本，在ubuntu系统上是没问题。[compile result](https://github.com/taosdata/taoskeeper/actions/runs/3088874181/jobs/4995854268)

感谢，使用 1.17版本搞定了。

**Comment by sangshuduo** [comment]
> 1. check sum 各种报错，最后只好手动调成一致
> 
>     2. 要求influxdata/telegraf@v1.23.3  但是它又要求harlow/kinesis-consumer v0.3.6 ，但是这个版本被作者删了，根本都不存在了，也不知的怎么改，我就把telegraf版本改成1.24.0 不知道最后行不行
> 
>     3. influxdata/telegraf改成1.24.0之后，requires  google.golang.org/grpc/naming@v0.0.0-00010101000000-000000000000 一个什么很奇怪的版本，也是根本找不到的，现在就卡在这里，根本没法继续安装了.....
> 
> 
> 求教程

设置 GOPROXY，可参考 https://github.com/taosdata/taoskeeper README
